### ISSUE TITLE
A downloader script for yande.re_db

### ISSUE THREAD

**Issue by ghost** [Beats0/scripter#1]
感觉在浏览器中一个个下载图片不是很友好，于是使用python写了一个一键下载的脚本  
希望能有一些帮助
项目地址在 https://github.com/shuye02/yande.re_db-downloader

**Comment by Beats0** [comment]
不是有批量下载吗，download mode的按钮
下载速度也是秒开啊

**pc端更注重的是图片预览功能**

**Comment by ghost** [comment]
批量下载一次只能下载一页（50张图片）

**Comment by mokurin000** [comment]
> 
> 
> 感觉在浏览器中一个个下载图片不是很友好，于是使用python写了一个一键下载的脚本
> 希望能有一些帮助
> 项目地址在 https://github.com/shuye02/yande.re_db-downloader

https://github.com/poly000/booru_spider/tree/zh_CN.ver
也许能被用到emmm
