### ISSUE TITLE
关于Booru-Selector-Downloader

### ISSUE THREAD

**Issue by mokurin000** [Beats0/scripter#2]
Booru-Selector-Downloader有没有考虑raikou2.donmai.us托管的图……
我不懂js，不知道有没有，所以想问一下是不是遗漏了
如：<b>https://raikou2.donmai.us/f7/3d/f73df5b2336bb784739a0163995113fe.jpg</b>
顺便膜一下大佬

**Comment by mokurin000** [comment]
结果是 https://danbooru.donmai.us/data/f73df5b2336bb784739a0163995113fe.png
报错403
正确的是 https://raikou2.donmai.us/<b>f7</b>/<b>3d</b>/f73df5b2336bb784739a0163995113fe.jpg

这里等大佬解决…… 判断403或者解析json？

**Comment by mokurin000** [comment]
![图片](https://user-images.githubusercontent.com/34085039/62538114-9b2b2280-b884-11e9-92b4-25e3ea0aae44.png)
像这样子

**Comment by mokurin000** [comment]
因为本萌新不会JS…… 只能等大佬填坑了

**Comment by Beats0** [comment]
图片文件名`png`称服务器找不到资源所以报403，一般`jpg`或`png`切换后缀即可, 到时候判断图片响应状态切换文件名应该就可以了
最近忙，可能周末才会更新吧 (￣▽￣)

**Comment by mokurin000** [comment]
七夕忙…… emmm 是时候放火了（

**Comment by mokurin000** [comment]
https://raikou1.donmai.us/0e/fd/0efd0c2c785ff8350d88f82a2b0e58e0.png
emmm
今天下载danbooru所有初音标签的图时发现的

**Comment by mokurin000** [comment]
然后
https://raikou1.donmai.us/a0/79/a079616e92042921c05f0efd07d22ee3.gif
https://raikou1.donmai.us/06/d4/06d4917f809d30e711aa2b9e2a5d2691.jpeg
https://raikou2.donmai.us/7c/74/7c74ec5cb4b0b5bcb785726b6ee51afe.zip
https://danbooru.donmai.us/data/ed606e0dd9da0688649b8933748e525c.zip
raikou1没有发现有zip文件...
raikou2和data没发现有jpeg文件，但有GIF文件
也许raikou1也会有其他文件…… 不清楚emmm

**Comment by mokurin000** [comment]
啊啊。。https://danbooru.donmai.us/data/ed606e0dd9da0688649b8933748e525c.zip 403了
我下载完就被删除了？……

**Comment by Beats0** [comment]
不支持gif 和 jpeg，太麻烦了 (

**Comment by Beats0** [comment]
哦哦，有个 `data-file-url`， 这个就是源文件地址，到时候改一下就行了

![](https://ws1.sinaimg.cn/large/006nOlwNly1g5t7cmb6vqj30vn05i0tv.jpg)

**Comment by mokurin000** [comment]
emmm zip呢 QAQ

**Comment by poly000** [comment]
> 件名应该就可以了
emmm
周一了

**Comment by mokurin000** [comment]
> 
> 
> 图片文件名`png`称服务器找不到资源所以报403，一般`jpg`或`png`切换后缀即可, 到时候判断图片响应状态切换文件名应该就可以了
> 最近忙，可能周末才会更新吧 (￣▽￣)


emmm
已经周一了

**Comment by Beats0** [comment]
fixed https://github.com/Beats0/scripter/commit/3f41e863fa05ffbb88af9ce862de9d0692a7aaa6

图片验证， 如果 `.jpg` 图片并不存在就切换到 `.png`
https://github.com/Beats0/scripter/blob/3f41e863fa05ffbb88af9ce862de9d0692a7aaa6/Booru-Selector-Downloader/myselect.js#L132-L147

**Comment by mokurin000** [comment]
> 
> 
> fixed [3f41e86](https://github.com/Beats0/scripter/commit/3f41e863fa05ffbb88af9ce862de9d0692a7aaa6)
> 
> 图片验证， 如果 `.jpg` 图片并不存在就切换到 `.png`
> 
> https://github.com/Beats0/scripter/blob/3f41e863fa05ffbb88af9ce862de9d0692a7aaa6/Booru-Selector-Downloader/myselect.js#L132-L147

emmm gif不管了吗（）

**Comment by Beats0** [comment]
danbooru是可以下载gif的, 直接提取图片地址
logJson数据格式为

```js
[{"id":"3583914","md5":"123fe221874ece11e9d9357578c37090","largeFileUrl":"https://danbooru.donmai.us/data/123fe221874ece11e9d9357578c37090.gif","fileUrl":"https://danbooru.donmai.us/data/123fe221874ece11e9d9357578c37090.gif"}]
```
